import type { CrmState } from "@/lib/portal";

// Clearly fictional records for an empty workspace. Never replace an existing CRM row.
export function demoState(): CrmState {
  const at=(days:number)=>new Date(Date.now()-days*86400000).toISOString();
  const day=(days:number)=>at(days).slice(0,10);
  const clients=[
    {id:"demo-c1",demo:true,name:"Karim El Fassi",business:"Dar Nour Cosmetics · SAMPLE",phone:"+212 600 000 101",email:"karim@example.com",website:"https://example.com/darnour",markets:"Morocco, France",manager:"Salma Idrissi",status:"Active",createdAt:at(62),platformRequirements:[{platform:"Meta",requiredAccounts:2,bmId:"BM-DEMO-101",feePercent:4},{platform:"Google",requiredAccounts:1,bmId:"BM-DEMO-101",feePercent:6}]},
    {id:"demo-c2",demo:true,name:"Nadia Berrada",business:"Atlas Wear · SAMPLE",phone:"+212 600 000 102",email:"nadia@example.com",website:"https://example.com/atlas",markets:"Saudi Arabia, UAE",manager:"Omar Benali",status:"Active",createdAt:at(43),platformRequirements:[{platform:"TikTok",requiredAccounts:1,bmId:"",feePercent:5},{platform:"Snapchat",requiredAccounts:1,bmId:"",feePercent:7}]},
    {id:"demo-c3",demo:true,name:"Hamza Tazi",business:"TaziTech · SAMPLE",phone:"+212 600 000 103",email:"hamza@example.com",website:"https://example.com/tazitech",markets:"Morocco",manager:"Salma Idrissi",status:"Onboarding",createdAt:at(12),platformRequirements:[{platform:"Meta",requiredAccounts:1,bmId:"BM-DEMO-103",feePercent:4}]},
    {id:"demo-c4",demo:true,name:"Sara Lahlou",business:"Lahlou Home · SAMPLE",phone:"+212 600 000 104",email:"sara@example.com",website:"https://example.com/lahlou",markets:"Morocco",manager:"Omar Benali",status:"Onboarding",createdAt:at(2),platformRequirements:[{platform:"Google",requiredAccounts:1,bmId:"BM-DEMO-104",feePercent:8}]},
  ];
  const accounts=[
    {id:"demo-a1",demo:true,clientId:"demo-c1",name:"Dar Nour · Meta 01 · SAMPLE",accountId:"act_DEMO_482901",platform:"Meta",bmId:"BM-DEMO-101",region:"Europe",timezone:"Africa/Casablanca",feePercent:4,manager:"Salma Idrissi",status:"Active",workflowStage:"active",workflow:{sellingPrice:89,paymentVerified:true,supplier:"Demo Supplier"},pageLinks:["https://facebook.com/darnour-demo"],createdAt:at(59),activatedAt:at(56)},
    {id:"demo-a2",demo:true,clientId:"demo-c1",name:"Dar Nour · Meta 02 · SAMPLE",accountId:"act_DEMO_482902",platform:"Meta",bmId:"BM-DEMO-101",region:"China",timezone:"Africa/Casablanca",feePercent:4,manager:"Salma Idrissi",status:"Active",workflowStage:"active",workflow:{sellingPrice:69,paymentVerified:true,supplier:"Demo Supplier"},pageLinks:[],createdAt:at(31),activatedAt:at(29)},
    {id:"demo-a3",demo:true,clientId:"demo-c1",name:"Dar Nour · Google 01 · SAMPLE",accountId:"GOOGLE-DEMO-901",platform:"Google",bmId:"BM-DEMO-101",region:"Europe",timezone:"Africa/Casablanca",feePercent:6,manager:"Salma Idrissi",status:"In setup",workflowStage:"setup",workflow:{sellingPrice:69,supplier:"Demo Supplier",purchaseCost:38,dateOrdered:day(4),setupNotes:"Sample supplier order being prepared."},pageLinks:[],createdAt:at(5)},
    {id:"demo-a4",demo:true,clientId:"demo-c2",name:"Atlas Wear · TikTok 01 · SAMPLE",accountId:"TT-DEMO-60748",platform:"TikTok",bmId:"",region:"",timezone:"Asia/Riyadh",feePercent:5,manager:"Omar Benali",status:"Active",workflowStage:"active",workflow:{sellingPrice:39,paymentVerified:true},pageLinks:[],createdAt:at(40),activatedAt:at(37)},
    {id:"demo-a5",demo:true,clientId:"demo-c2",name:"Atlas Wear · Snapchat 01 · SAMPLE",accountId:"SNAP-DEMO-3159",platform:"Snapchat",bmId:"",region:"",timezone:"Asia/Riyadh",feePercent:7,manager:"Omar Benali",status:"Suspended",workflowStage:"issues",workflow:{sellingPrice:49,problem:"Sample restricted account",nextAction:"Ask supplier for review",deadline:day(1)},pageLinks:[],createdAt:at(23)},
    {id:"demo-a6",demo:true,clientId:"demo-c3",name:"TaziTech · Meta 01 · SAMPLE",accountId:"",platform:"Meta",bmId:"BM-DEMO-103",region:"Europe",timezone:"Africa/Casablanca",feePercent:4,manager:"Salma Idrissi",status:"Requested",workflowStage:"new",workflow:{sellingPrice:89,accountType:"Meta · Europe"},pageLinks:["https://facebook.com/tazitech-demo"],createdAt:at(3)},
    {id:"demo-a7",demo:true,clientId:"demo-c4",name:"Lahlou Home · Google 01 · SAMPLE",accountId:"",platform:"Google",bmId:"BM-DEMO-104",region:"China",timezone:"Africa/Casablanca",feePercent:8,manager:"Omar Benali",status:"Requested",workflowStage:"payment",workflow:{sellingPrice:49,paymentRequestSent:true,paymentReceived:false,paymentVerified:false},pageLinks:[],createdAt:at(1)},
  ];
  const payments=[
    {id:"demo-p1",demo:true,clientId:"demo-c1",accountId:"demo-a1",purpose:"account",amount:89,amountUsd:89,currency:"USD",method:"CIH Bank",reference:"SAMPLE-ORDER-01",status:"Verified",date:day(58),createdAt:at(58)},
    {id:"demo-p2",demo:true,clientId:"demo-c1",accountId:"demo-a1",topupId:"demo-t1",purpose:"topup",amount:500,amountUsd:500,currency:"USD",method:"Attijariwafa bank",reference:"SAMPLE-TOPUP-01",status:"Verified",date:day(7),createdAt:at(7)},
    {id:"demo-p3",demo:true,clientId:"demo-c1",accountId:"demo-a2",topupId:"demo-t2",purpose:"topup",amount:850,amountUsd:850,currency:"USD",method:"Wise",reference:"SAMPLE-TOPUP-02",status:"Verified",date:day(2),createdAt:at(2)},
    {id:"demo-p4",demo:true,clientId:"demo-c2",accountId:"demo-a4",topupId:"demo-t3",purpose:"topup",amount:1200,amountUsd:1200,currency:"USD",method:"Payoneer",reference:"SAMPLE-TOPUP-03",status:"Pending",date:day(0),createdAt:at(0)},
    {id:"demo-p5",demo:true,clientId:"demo-c3",accountId:"demo-a6",topupId:"demo-t4",purpose:"topup",amount:300,amountUsd:300,currency:"USD",method:"Cash Plus",reference:"SAMPLE-TOPUP-04",status:"Verified",date:day(1),createdAt:at(1)},
  ];
  const topups=[
    {id:"demo-t1",demo:true,clientId:"demo-c1",accountId:"demo-a1",paymentId:"demo-p2",platform:"Meta",accountName:accounts[0].name,adAccountId:accounts[0].accountId,amount:500,amountUsd:500,currency:"USD",feePercent:4,feeUsd:20,netUsd:480,provider:"Attijariwafa bank",manager:"Salma Idrissi",status:"Completed",createdAt:at(7)},
    {id:"demo-t2",demo:true,clientId:"demo-c1",accountId:"demo-a2",paymentId:"demo-p3",platform:"Meta",accountName:accounts[1].name,adAccountId:accounts[1].accountId,amount:850,amountUsd:850,currency:"USD",feePercent:4,feeUsd:34,netUsd:816,provider:"Wise",manager:"Salma Idrissi",status:"Completed",createdAt:at(2)},
    {id:"demo-t3",demo:true,clientId:"demo-c2",accountId:"demo-a4",paymentId:"demo-p4",platform:"TikTok",accountName:accounts[3].name,adAccountId:accounts[3].accountId,amount:1200,amountUsd:1200,currency:"USD",feePercent:5,feeUsd:60,netUsd:1140,provider:"Payoneer",manager:"Omar Benali",status:"Payment review",createdAt:at(0)},
    {id:"demo-t4",demo:true,clientId:"demo-c3",accountId:"demo-a6",paymentId:"demo-p5",platform:"Meta",accountName:accounts[5].name,adAccountId:"",amount:300,amountUsd:300,currency:"USD",feePercent:4,feeUsd:12,netUsd:288,provider:"Cash Plus",manager:"Salma Idrissi",status:"Processing",createdAt:at(1)},
  ];
  return {
    demoWorkspace:true,demoFinanceSeeded:true,demoWorkflowSeeded:true,
    clients,accounts,payments,topups,
    managers:[{id:"demo-m1",demo:true,name:"Salma Idrissi",email:"salma@example.com",phone:"+212 600 000 201",createdAt:at(80)},{id:"demo-m2",demo:true,name:"Omar Benali",email:"omar@example.com",phone:"+212 600 000 202",createdAt:at(80)}],
    agencyExpenses:[{id:"demo-e1",demo:true,date:day(10),category:"Client acquisition ads",platform:"Meta",amount:240,amountUsd:240,currency:"USD",vendor:"Meta Ads",description:"SAMPLE · lead acquisition",createdAt:at(10)},{id:"demo-e2",demo:true,date:day(4),category:"Account / inventory purchase",platform:"Google",linkedAccountId:"demo-a3",source:"workflow",amount:38,amountUsd:38,currency:"USD",vendor:"Demo Supplier",description:"SAMPLE · Google account purchase",createdAt:at(4)},{id:"demo-e3",demo:true,date:day(3),category:"Software & tools",amount:29,amountUsd:29,currency:"USD",vendor:"Demo tool",description:"SAMPLE · software",createdAt:at(3)}],
    agencyIncome:[],academy:[{id:"demo-l1",demo:true,title:"How to prepare your ad account request · SAMPLE",topic:"Accounts",url:"https://www.youtube.com/",notes:"Add your own training video here.",createdAt:at(5)},{id:"demo-l2",demo:true,title:"Payment proof checklist · SAMPLE",topic:"Payments",url:"",notes:"A sample guide. Replace with your own video and instructions.",createdAt:at(2)}],
    receivingMethods:[{id:"demo-r1",demo:true,name:"CIH Bank",holder:"SAMPLE · replace before sharing",details:"DEMO ONLY · no real account",currency:"MAD",country:"Morocco",createdAt:at(2)}],disabledMethods:[],
    activity:[{text:"SAMPLE · TaziTech requested a Meta account",kind:"client",recordId:"demo-c3",clientId:"demo-c3",createdAt:at(3)},{text:"SAMPLE · Dar Nour top-up completed",kind:"topup",recordId:"demo-t2",clientId:"demo-c1",createdAt:at(2)},{text:"SAMPLE · Atlas Wear payment awaiting review",kind:"payment",recordId:"demo-p4",clientId:"demo-c2",createdAt:at(0)}],accessGrants:[],
  };
}
