"use client";

import { useEffect, useMemo, useState } from "react";
import { SubmitForm } from "./portal-forms";

type Row = Record<string,any>;
type PortalData={role:"client"|"manager";label:string;email:string;permissions:string[];preview?:boolean;overview:Row|null;clients:Row[];ownClient:Row|null;accounts:Row[];requestClients:Row[];requestTopupAccounts:Row[];paymentAccounts:Row[];paymentMethods:Row[];topups:Row[];payments:Row[];academy:Row[];activity:Row[]};
const tabs=[ ["overview","Overview","overview"],["clients","Clients","person"],["accounts","Subscriptions","accounts"],["topups","Top-ups","topup"],["payments","Payments","receipt"],["requestAccounts","Request account","workflow"],["requestTopups","Request top-up","topup"],["submitPayments","Submit payment","receipt"],["academy","Academy","academy"],["activity","Activity","activity"] ];
const platforms=[{id:"Meta",name:"Meta Ads",logo:"meta.svg"},{id:"TikTok",name:"TikTok Ads",logo:"tiktok.svg"},{id:"Google",name:"Google Ads",logo:"googleads.svg"},{id:"Snapchat",name:"Snapchat Ads",logo:"snapchat.svg"}];
const money=(v:unknown)=>`$${Number(v||0).toLocaleString("en-US",{maximumFractionDigits:2})}`;
const date=(v:unknown)=>v?new Date(String(v)).toLocaleString("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Africa/Casablanca"}):"—";
const brand=(p:string)=><span className="portal-brand"><img src={`/icons/${platforms.find(x=>x.id===p)?.logo||"meta.svg"}`} alt=""/>{platforms.find(x=>x.id===p)?.name||p}</span>;
const status=(s:string)=><span className={`portal-status ${(s||"").toLowerCase().replace(/\W+/g,"-")}`}>{s||"—"}</span>;
const item=(label:string,value:unknown)=><div className="portal-metric"><small>{label}</small><strong>{String(value??"—")}</strong></div>;
const empty=(message:string)=><div className="portal-empty">{message}</div>;
const initialItems=()=>platforms.map(p=>({platform:p.id,selected:false,count:1,region:"Europe",bmId:"",pages:""}));

export default function PortalClient({email,signOutHref,previewQuery="",adminPreview=false}:{email:string;signOutHref:string;previewQuery?:string;adminPreview?:boolean}){
  const [data,setData]=useState<PortalData|null>(null),[error,setError]=useState(""),[tab,setTab]=useState("overview"),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
  const [requestClient,setRequestClient]=useState(""),[timezone,setTimezone]=useState("Africa/Casablanca"),[notes,setNotes]=useState(""),[items,setItems]=useState(initialItems);
  const [editingClient,setEditingClient]=useState<Row|null>(null);
  useEffect(()=>{void refresh();},[]);
  async function refresh(){try{const res=await fetch(`/api/portal${previewQuery?`?${previewQuery}`:""}`,{cache:"no-store"}),json=await res.json() as PortalData&{error?:string};if(!res.ok)throw new Error(json.error||"Could not load workspace");setData(json);setError("");setRequestClient(v=>v||json.ownClient?.id||json.requestClients?.[0]?.id||"");if(!json.permissions.includes(tab))setTab(json.permissions.includes("overview")?"overview":json.permissions[0]||"overview");}catch(e){setError(e instanceof Error?e.message:"Could not load workspace");}}
  const allowed=useMemo(()=>tabs.filter(([key])=>data?.permissions.includes(key)),[data]);
  const accounts=data?.accounts||[],topups=data?.topups||[],payments=data?.payments||[];
  const names=Object.fromEntries((data?.clients||[]).map(c=>[c.id,c.business]));if(data?.ownClient)names[data.ownClient.id]=data.ownClient.business;
  const accountNames=Object.fromEntries(accounts.map(a=>[a.id,a.name]));
  const matched=(rows:Row[])=>rows.filter(row=>JSON.stringify(row).toLowerCase().includes(query.toLowerCase()));
  function changeItem(index:number,patch:Row){setItems(old=>old.map((x,i)=>i===index?{...x,...patch}:x));}
  async function requestAccounts(){
    if(adminPreview){setNotice("Preview only. Sign in as this client to submit a request.");return;}
    const selected=items.filter(x=>x.selected).map(x=>({platform:x.platform,count:Number(x.count),region:["Meta","Google"].includes(x.platform)?x.region:"",bmId:x.bmId.trim(),pages:x.platform==="Meta"?x.pages.split(/\n/).map(s=>s.trim()).filter(Boolean):[]}));
    if(!selected.length){setNotice("Choose at least one platform.");return;}
    setBusy(true);setNotice("");
    try{const res=await fetch("/api/portal/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({clientId:requestClient,items:selected,timezone,notes})}),json=await res.json() as {error?:string;created:number};if(!res.ok)throw new Error(json.error);
      setNotice(`${json.created} account request${json.created===1?"":"s"} sent to your agency.`);setItems(initialItems());setNotes("");await refresh();
    }catch(e){setNotice(e instanceof Error?e.message:"Could not send request.");}finally{setBusy(false);}
  }
  async function logout(){await fetch("/api/auth/logout",{method:"POST",headers:{"Content-Type":"application/json"}});window.location.assign("/login");}
  async function saveClient(){if(!editingClient||adminPreview)return;setBusy(true);setNotice("");try{const res=await fetch("/api/portal/clients",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editingClient)});const json=await res.json() as {error?:string};if(!res.ok)throw new Error(json.error||"Could not save client.");setEditingClient(null);setNotice("Client details saved.");await refresh();}catch(e){setNotice(e instanceof Error?e.message:"Could not save client.");}finally{setBusy(false)}}
  if(error)return <main className="portal-gate"><img src="/logo-green.png" alt="Adsolution"/><h1>Workspace access</h1><p>{error}</p><p>Signed in as {email}. Ask the admin to check this account in People & access.</p>{adminPreview?<a href="/access">Back to Admin</a>:<button className="portal-primary" type="button" onClick={logout}>Sign out</button>}</main>;
  if(!data)return <main className="portal-gate"><img src="/logo-green.png" alt="Adsolution"/><h1>Loading workspace…</h1></main>;
  return <div className="portal-app"><aside className="portal-sidebar"><div className="portal-logo"><img src="/logo-green.png" alt="Adsolution"/><small>{data.role.toUpperCase()} WORKSPACE</small></div><nav>{allowed.map(([key,label,icon])=><button key={key} className={tab===key?"active":""} onClick={()=>{setTab(key);setQuery("");setNotice("");}}><svg aria-hidden="true"><use href={`/icons/ui.svg#${icon}`}/></svg><span>{label}</span></button>)}</nav><div className="portal-user"><strong>{data.label}</strong><small>{data.email}</small>{adminPreview?<a href={signOutHref}>Exit preview</a>:<button className="portal-logout" type="button" onClick={logout}>Sign out</button>}</div></aside>
    <div className="portal-main"><header className="portal-top"><span>Adsolution <b>/</b> {tabs.find(x=>x[0]===tab)?.[1]}</span><div>{adminPreview?"ADMIN PREVIEW":data.role==="client"?"Client portal":"Manager portal"}</div></header><main className="portal-content">{adminPreview&&<div className="portal-preview-note">Preview only · <a href="/access">Back to People & access</a></div>}
      <div className="portal-heading"><div><small>YOUR WORKSPACE</small><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1><p>{data.label} · Only the information assigned to this account appears here.</p></div>{tab!=="overview"&&!["requestAccounts","requestTopups","submitPayments"].includes(tab)&&<input className="portal-search" type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records"/>}</div>
      {tab==="overview"&&data.overview&&<><div className="portal-metrics">{item("Ad accounts",data.overview.accounts)}{item("Active subscriptions",data.overview.activeAccounts)}{item("Open requests",data.overview.openRequests)}{item("Completed top-ups",data.overview.completedTopups)}{item("Top-up volume",money(data.overview.topupVolume))}{item("Pending payments",data.overview.pendingPayments)}</div><div className="portal-two"><section className="portal-panel"><h2>Recent subscriptions</h2>{accounts.slice(0,4).map(a=><div className="portal-list" key={a.id}><span>{brand(a.platform)}<small>{a.name}</small></span>{status(a.status)}</div>)}{!accounts.length&&empty("No account records yet.")}</section><section className="portal-panel"><h2>Recent top-ups</h2>{topups.slice(0,4).map(t=><div className="portal-list" key={t.id}><span><strong>{money(t.amountUsd)}</strong><small>{accountNames[t.accountId]||"Ad account"} · {date(t.createdAt)}</small></span>{status(t.status)}</div>)}{!topups.length&&empty("No top-ups yet.")}</section></div></>}
      {tab==="clients"&&<>{notice&&<p role="status" className="portal-notice">{notice}</p>}<div className="portal-cards">{matched(data.clients).map(c=><article className="portal-panel" key={c.id}><div className="portal-person-avatar">{String(c.business||"C").slice(0,2).toUpperCase()}</div><h2>{c.business}</h2><p>{c.name} · {c.markets||"—"}</p><dl><dt>Phone</dt><dd>{c.phone||"—"}</dd><dt>Email</dt><dd>{c.email||"—"}</dd><dt>Website</dt><dd>{c.website||"—"}</dd></dl>{data.role==="manager"&&!adminPreview&&<button className="portal-edit" type="button" onClick={()=>setEditingClient({...c})}>Edit client details</button>}</article>)}{!matched(data.clients).length&&empty("No clients assigned to you.")}</div>{editingClient&&<div className="portal-edit-backdrop" role="presentation"><section className="portal-edit-dialog" role="dialog" aria-modal="true" aria-label="Edit client"><h2>Edit {editingClient.business}</h2>{["name","phone","email","website","markets"].map(key=><label key={key}>{key[0].toUpperCase()+key.slice(1)}<input value={editingClient[key]||""} onChange={e=>setEditingClient(c=>({...c,[key]:e.target.value}))}/></label>)}<div><button className="portal-edit" type="button" onClick={()=>setEditingClient(null)}>Cancel</button><button className="portal-primary" type="button" disabled={busy} onClick={saveClient}>{busy?"Saving…":"Save client"}</button></div></section></div>}</>}
      {tab==="accounts"&&<section className="portal-panel"><h2>Ad account subscriptions</h2><div className="portal-table-wrap"><table><thead><tr><th>Account</th>{data.role==="manager"&&<th>Client</th>}<th>Platform</th><th>Account ID</th><th>Origin</th><th>Status</th></tr></thead><tbody>{matched(accounts).map(a=><tr key={a.id}><td><strong>{a.name}</strong><small>Requested {date(a.createdAt)}</small></td>{data.role==="manager"&&<td>{names[a.clientId]||"—"}</td>}<td>{brand(a.platform)}</td><td>{a.accountId||"Pending"}</td><td>{a.region||"Standard"}</td><td>{status(a.status)}</td></tr>)}</tbody></table></div>{!matched(accounts).length&&empty("No subscriptions yet. Request an account to start.")}</section>}
      {tab==="topups"&&<section className="portal-panel"><h2>Funding history</h2><div className="portal-table-wrap"><table><thead><tr><th>Date</th><th>Ad account</th><th>Platform</th><th>Amount</th><th>Fee</th><th>Net credited</th><th>Status</th></tr></thead><tbody>{matched(topups).map(t=><tr key={t.id}><td>{date(t.createdAt)}</td><td>{accountNames[t.accountId]||"Ad account"}</td><td>{brand(t.platform||accounts.find(a=>a.id===t.accountId)?.platform)}</td><td>{money(t.amountUsd)}</td><td>{money(t.feeUsd)}</td><td>{money(Number(t.amountUsd)-Number(t.feeUsd||0))}</td><td>{status(t.status)}</td></tr>)}</tbody></table></div>{!matched(topups).length&&empty("No top-ups yet.")}</section>}
      {tab==="payments"&&<section className="portal-panel"><h2>Payments & proofs</h2><div className="portal-table-wrap"><table><thead><tr><th>Date</th><th>For</th><th>Amount</th><th>Method</th><th>Status</th><th>Proof</th></tr></thead><tbody>{matched(payments).map(p=><tr key={p.id}><td>{date(p.createdAt)}</td><td>{accountNames[p.accountId]||"General payment"}</td><td>{p.amount} {p.currency}</td><td>{p.method||"—"}</td><td>{status(p.status)}</td><td>{p.proofUrl?<a href={p.proofUrl} target="_blank" rel="noreferrer">View proof ↗</a>:p.proof?"Filename only":"—"}</td></tr>)}</tbody></table></div>{!matched(payments).length&&empty("No payments yet.")}</section>}
      {tab==="academy"&&<div className="portal-cards">{matched(data.academy).map(a=><article className="portal-panel" key={a.id}><div className="portal-lesson-icon">▶</div><small>{a.topic||"Guide"}</small><h2>{a.title}</h2><p>{a.notes}</p>{a.url&&<a href={a.url} target="_blank" rel="noreferrer">Watch video ↗</a>}</article>)}{!matched(data.academy).length&&empty("No lessons published yet.")}</div>}
      {tab==="activity"&&<section className="portal-panel"><h2>Activity</h2>{matched(data.activity).map((a,i)=><div className="portal-list" key={i}><span><strong>{a.text}</strong><small>{date(a.createdAt)}</small></span></div>)}{!matched(data.activity).length&&empty("No activity yet.")}</section>}
      {tab==="requestTopups"&&<>{notice&&<p role="status" className="portal-notice">{notice}</p>}<SubmitForm mode="topup" role={data.role} clients={data.requestClients} accounts={data.requestTopupAccounts} methods={data.paymentMethods} disabled={adminPreview} onDone={m=>{setNotice(m);void refresh();}}/></>}
      {tab==="submitPayments"&&<>{notice&&<p role="status" className="portal-notice">{notice}</p>}<SubmitForm mode="payment" role={data.role} clients={data.requestClients} accounts={data.paymentAccounts} methods={data.paymentMethods} disabled={adminPreview} onDone={m=>{setNotice(m);void refresh();}}/></>}
      {tab==="requestAccounts"&&<section className="portal-panel portal-request"><h2>Request ad accounts</h2><p>Select one or more platforms. Each account will appear in your subscriptions and in the agency workflow.</p>{data.role==="manager"&&<label>Client<select value={requestClient} onChange={e=>setRequestClient(e.target.value)}>{data.requestClients.map(c=><option key={c.id} value={c.id}>{c.business}</option>)}</select></label>}
        <div className="portal-request-grid">{items.map((x,index)=><div className={`portal-platform ${x.selected?"selected":""}`} key={x.platform}><label className="portal-platform-head"><input type="checkbox" checked={x.selected} onChange={e=>changeItem(index,{selected:e.target.checked})}/>{brand(x.platform)}</label>{x.selected&&<div className="portal-platform-fields"><label>Number of accounts<input type="number" min="1" max="5" value={x.count} onChange={e=>changeItem(index,{count:Number(e.target.value)})}/></label>{["Meta","Google"].includes(x.platform)&&<label>Origin<select value={x.region} onChange={e=>changeItem(index,{region:e.target.value})}><option>Europe</option><option>China</option></select></label>}<label>BM / Business ID<input value={x.bmId} onChange={e=>changeItem(index,{bmId:e.target.value})} placeholder="If available"/></label>{x.platform==="Meta"&&<label>Facebook Page links (one per line)<textarea value={x.pages} onChange={e=>changeItem(index,{pages:e.target.value})} placeholder="https://facebook.com/yourpage"/></label>}</div>}</div>)}</div>
        <div className="portal-request-foot"><label>Account time zone<select value={timezone} onChange={e=>setTimezone(e.target.value)}>{["UTC",...Intl.supportedValuesOf("timeZone")].map(t=><option key={t}>{t}</option>)}</select></label><label>Notes for your agency<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} placeholder="Optional details"/></label></div><button className="portal-primary" disabled={busy||adminPreview} onClick={requestAccounts}>{adminPreview?"Preview only":busy?"Sending…":"Send request"}</button>{notice&&<p role="status" className="portal-notice">{notice}</p>}
      </section>}
    </main></div></div>;
}
